service: crm-service
plugins:
  - serverless-wsgi
  - serverless-stage-manager
  - serverless-domain-manager
frameworkVersion: '2'
custom: ${file(resources/customs.yml)}
provider:
  name: aws
  stage: ${opt:stage,'dev'}
  runtime: python3.8
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    API_GATEWAY_BASE_PATH: ${self:custom.customDomain.basePath}
    DB_NAME: ${self:custom.DB_NAME.${self:provider.stage}}
    DB_USERNAME: ${self:custom.DB_USERNAME.${self:provider.stage}}
    DB_HOST: ${self:custom.DB_HOST.${self:provider.stage}}
    DB_PASSWORD: ${self:custom.DB_PASSWORD.${self:provider.stage}}
    DEBUG: ${self:custom.DEBUG.${self:provider.stage}}
    ENVIRONMENT: ${self:custom.ENVIRONMENT.${self:provider.stage}}
    AWS_POOL_ID: ${self:custom.AWS_POOL_ID.${self:provider.stage}}
    AWS_IDENTITY_POOL_ID: ${self:custom.AWS_IDENTITY_POOL_ID.${self:provider.stage}}
    AWS_COGNITO_CLIENT_ID: ${self:custom.AWS_COGNITO_CLIENT_ID.${self:provider.stage}}
    BUCKET_NAME: ${self:custom.BUCKET_NAME.${self:provider.stage}}
    REGION: "us-east-1"
package: ${file(resources/package.yml)}
functions:
  - ${file(resources/app.yml)}
