service: oion-employee-svc
plugins:
  - serverless-wsgi
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-python-requirements
frameworkVersion: '2'
custom: ${file(resources/customs.yml)}
provider:
  name: aws
  stage: ${opt:stage,'dev'}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource: "arn:aws:s3:::*"
  runtime: python3.8
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    API_GATEWAY_BASE_PATH: ${self:custom.customDomain.basePath}
    ENVIRONMENT: ${self:custom.ENVIRONMENT.${self:provider.stage}}
    EMPLOYEES_CSV_OBJECT_KEY: ${self:custom.EMPLOYEES_CSV_OBJECT_KEY.${self:provider.stage}}
    S3_BUCKET_NAME: ${self:custom.S3_BUCKET_NAME.${self:provider.stage}}
package: ${file(resources/package.yml)}
functions:
  - ${file(resources/app.yml)}
